ALTER TABLE label ADD COLUMN street VARCHAR(255);
ALTER TABLE label ADD COLUMN street2 VARCHAR(255);
ALTER TABLE label ADD COLUMN city VARCHAR(255);
ALTER TABLE label ADD COLUMN postal_code VARCHAR(50);
ALTER TABLE label ADD COLUMN country VARCHAR(100);
